In [2]:
import numpy as np

## 1. What is a Python library? Why we use Python libraries?

## ANS.
Python library is a set of collection of functions.In which user have advantge to perform specific functions in very low time and reduce memory.


## 2. What is the difference between Numpy array and List?

## ANS.
## NUMPY ARRAY
Numpy arrays are multidimensional.

Numpy arrays come with a wide range of mathematical operations 

Numpy arrays are homogenous.

Numpy arrays offer advanced indexing and slicing capabilities, including boolean and fancy indexing.

If you dealing with numerical data and need efficient compution the numpy arrays are the best choice.

NUmpy arrays are more memory efficient because they use the same data type in a continuous location.

## NUMPY LIST

They are more general-purpose, have slow speed, and are not best for numerical purposes.

They are less memory efficient.

They do not natively support element-wise operations or broadcasting. You would need to use loops or list comprehensions for similar functionality, which is less efficient.

They are heterogeneous, allowing elements of different data types to be stored in the same list.

They can be nested to create multidimensional structures, but operations on them are less straightforward and less efficient.

They support basic slicing and indexing but lack the advanced capabilities of NumPy arrays.

## 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.size

12

In [6]:
arr.shape

(3, 4)

In [7]:
arr.ndim

2

## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
arr[0]

array([1, 2, 3, 4])

## 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [22]:
arr[2,3]

12

## 6. Write code to extract all odd-indexed elements from the given numpy array.

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
import numpy as np

# Creating the NumPy array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extracting elements at odd-indexed rows and columns
odd_indexed_elements = array[1::2, 1::2]

print(odd_indexed_elements)


[[6 8]]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [24]:
random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.89902536 0.82326342 0.89745978]
 [0.26326087 0.75324681 0.35509688]
 [0.07657373 0.20172925 0.66817184]]


## 8. Describe the difference between np.random.rand and np.random.randn?

## ANS:
random. rand() produces random numbers from a uniform distribution over the interval [0, 1), while np. random. randn() generates random numbers from a standard normal distribution

## 9. Write code to increase the dimension of the following array.

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [25]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [26]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr=np.expand_dims(arr,axis=0)

In [28]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [31]:
arr1=np.expand_dims(arr,axis=1)

In [32]:
arr1

array([[[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]]])

## 10. How to transpose the following array in NumPy?

In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [35]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [61]:

Matrix_A2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

Matrix_B2 =np.array([[1, 2, 3,4], [5,6,7,8],[9,10,11,12]])

In [62]:
#1.index wise multiplication
Matrix_A2 * Matrix_B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [63]:
#2.matrix multiplication
Matrix_A2=  np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

Matrix_B2 = np.array([[1, 2, 3], [4,5,6],[7,8,9],[ 10, 11, 12]])
Matrix_A2 @ Matrix_B2

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [64]:
# add both the matrix
Matrix_A2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

Matrix_B2 =np.array([[1, 2, 3,4], [5,6,7,8],[9,10,11,12]])

Matrix_A2 + Matrix_B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [66]:
#Subtract matrix B from A
Matrix_A2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

Matrix_B2 =np.array([[1, 2, 3,4], [5,6,7,8],[9,10,11,12]])
Matrix_B2 - Matrix_A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
Matrix_A2 - Matrix_B2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
# Diide Matix B by A
Matrix_A2 / Matrix_B2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
Matrix_B2 - Matrix_A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 12.  Which function in Numpy can be used to swap the byte order of an array?

In [70]:
import numpy as np

# Create an array with a specific byte order
array = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:", array)

# Swap the byte order
swapped_array = array.byteswap()
print("Byte-swapped array:", swapped_array)

# Verify the byte order has been swapped
print("Original array (after swap):", array)


Original array: [    1   256 65536]
Byte-swapped array: [16777216    65536      256]
Original array (after swap): [    1   256 65536]


## 13.  What is the significance of the np.linalg.inv function?

## 14. What does the np.reshape function do, and how is it used?

In [72]:

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array to a 2D array with shape (2, 3)
array_2d = np.reshape(array_1d, (2, 3))

print("Original array:")
print(array_1d)
print("\nReshaped array:")
print(array_2d)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


## 15. What is broadcasting in Numpy?

In [77]:
# """Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes.
# When performing operations on arrays, NumPy compares their shapes element-wise. If these shapes are compatible, NumPy
# "broadcasts" the smaller array across the larger array so that they have compatible shapes.
# Broadcasting is particularly useful because it eliminates the need to manually expand the smaller array.

arr=np.zeros((3,4))

In [78]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [80]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])